twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    # to render the form system with Bootstrap-friendly markup.
    form_themes:
        - bootstrap_4_layout.html.twig
